export enum IncorporationType {
  CHARITABLE_INCORPORATED_ORGANIZATION = 'charitable_incorporated_organization',
  CHARTERED_COMPANY = 'chartered_company',
  COOPERATIVE = 'cooperative',
  GOVERNMENTAL_ENTITY = 'governmental_entity',
  HOLDING_COMPANY = 'holding_company',
  PARTNERSHIP = 'partnership',
  LIMITED_PARTNERSHIP = 'limited_partnership',
  LIMITED_LIABILITY_PARTNERSHIP = 'limited_liability_partnership',
  OTHER = 'other',
  PRIVATE_LIMITED_COMPANY = 'private_limited_company',
  PUBLIC_LIMITED_COMPANY = 'public_limited_company',
  NON_PROFIT_ORGANIZATION = 'non_profit_organization',
  NON_GOVERNMENT_ORGANIZATION = 'non_government_organization',
  PROFESSIONAL_ASSOCIATION = 'professional_association',
  SOLE_PROPRIETORSHIP = 'sole_proprietorship',
  STATUTORY_COMPANY = 'statutory_company',
  SUBSIDIARY_COMPANY = 'subsidiary_company',
  TRUST = 'trust',
  UNLIMITED_COMPANY = 'unlimited_company',
  UNLIMITED_PARTNERSHIP = 'unlimited_partnership'
}